* An incomplete api spec

** Invitees

Invitees would need the following information:

#+BEGIN_SRC javascript :results silent
  {
    id: 0,
    name: "Sally",
    email: "inabarbieworld@aol.com",
    number: "123-456-7891"
  }
#+END_SRC

** Dates/Timeslots

Dates can be serialized in the usual ~YYYY-MM-DDTHH:MM:SS~ way. For
instance a timeslot object indicating the period on September 30th
from 12:30 to 4:30 pm might look like:

#+BEGIN_SRC javascript :results silent
  {
    id: 0,
    start: "2017-10-30T12:30:00",
    end: "2017-10-30T16:30:00",
    yes: [0, 3],
    no: [1]
  }
#+END_SRC

Where yes and no are just arrays with elements referencing the invitee
~id~ of the invitees that have responded with their availability for the event.

Timezones? keeping dates in whatever the fuck local time seems fine...

** Events

Owners could be inferred as the first invitee, but currently no spot
in the ui necessitates an owners name, therefore a special owner
property denoting the owner's email might be in order.

In general, an event might have the following structure:

#+BEGIN_SRC javascript :results silent
  {
    id: 0,
    name: "Vegan Barbecue",
    owner: "drodman@dprk.nk,"
    timeslots: [
      {
        id: 0,
        start: "2017-10-30T12:30:00",
        end: "2017-10-30T16:30:00",
        yes: [0],
        no: []
      },
      {
        id: 1,
        start: "2017-10-31T12:00:00",
        end: "2017-10-31T15:00:00",
        yes: [],
        no: [0]
      }
    ],
    invitees: [
      {
        id: 0,
        name: "Sally",
        email: "inabarbieworld@aol.com",
        number: "123-456-7891"
      },
      {
        id: 1,
        name: "Enrique",
        email: "enriqueiglasias@gmail.com",
        number: "123-321-1144"
      }
    ],
  }
#+END_SRC

Not sure if this is the best way to go about doing things, since
finding out who has responded to the event invite is a bit of a
detour... In the scenario above, only Sally has responded to the event
invite.
